# Generated by Django 4.0.6 on 2022-07-24 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='nombre', max_length=100)),
                ('last_name', models.CharField(db_column='apellido', max_length=100)),
                ('id_number', models.CharField(db_column='numero_identificacion', max_length=11)),
                ('id_type', models.CharField(choices=[('C', 'CEDULA'), ('E', 'PASAPORTE')], db_column='tipo_identificacion', default='C', max_length=1)),
                ('nationality', models.CharField(db_column='nacionalidad', max_length=60)),
                ('birth_date', models.DateField(db_column='fecha_nacimiento')),
                ('tel', models.CharField(db_column='telefono', max_length=10)),
                ('celphone', models.CharField(db_column='celular', max_length=10)),
                ('facebook', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'solicitante',
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('B', 'comercial'), ('V', 'vehiculos'), ('P', 'personal')], db_column='tipo_prestamo', default='P', max_length=2)),
                ('amount_requested', models.DecimalField(db_column='monto_solicitado', decimal_places=2, max_digits=14)),
                ('amount_approved', models.DecimalField(db_column='monto_aprovado', decimal_places=2, max_digits=14)),
                ('term', models.IntegerField(db_column='plazo')),
                ('referer', models.CharField(max_length=260)),
                ('status', models.CharField(choices=[('VALIDANDO', 'validando'), ('COMPLETADO', 'completado'), ('CANCELADO', 'cancelado'), ('APROVADO', 'aprovado')], db_column='estatus_solicitud', default='VALIDANDO', max_length=10)),
                ('applicant', models.OneToOneField(db_column='solicitante_id', on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='loanrequest.applicant')),
            ],
            options={
                'db_table': 'solicitud_prestamo',
            },
        ),
        migrations.CreateModel(
            name='EmploymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('PR', 'privado'), ('PU', 'publico'), ('SE', 'auto empleado')], db_column='estado_laboral', default='PR', max_length=2)),
                ('company_name', models.CharField(db_column='nombre_empresa', max_length=100)),
                ('tel', models.CharField(db_column='telefono', max_length=10)),
                ('tel_ext', models.CharField(db_column='extension_tel', max_length=4)),
                ('current_role', models.CharField(db_column='cargo_puesto', max_length=260)),
                ('start_date', models.DateField(db_column='fecha_ingreso')),
                ('monthly_salary', models.DecimalField(db_column='ingresos_mensuales', decimal_places=2, max_digits=14)),
                ('street', models.CharField(db_column='calle', max_length=260)),
                ('number', models.IntegerField(db_column='numero')),
                ('building', models.CharField(db_column='edificio', max_length=100)),
                ('town', models.CharField(db_column='sector', max_length=60)),
                ('city', models.CharField(db_column='ciudad', max_length=60)),
                ('state', models.CharField(db_column='provincia', max_length=100)),
                ('applicant', models.OneToOneField(db_column='solicitante_id', on_delete=django.db.models.deletion.CASCADE, related_name='employment_data', to='loanrequest.applicant')),
            ],
            options={
                'db_table': 'datos_laborales',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(db_column='calle', max_length=260)),
                ('number', models.IntegerField(db_column='numero')),
                ('building', models.CharField(db_column='edificio', max_length=100, null=True)),
                ('apartment', models.CharField(db_column='apartamento', max_length=10, null=True)),
                ('town', models.CharField(db_column='sector', max_length=60)),
                ('city', models.CharField(db_column='ciudad', max_length=60)),
                ('state', models.CharField(db_column='provincia', max_length=100)),
                ('applicant', models.OneToOneField(db_column='solicitante_id', on_delete=django.db.models.deletion.CASCADE, related_name='address', to='loanrequest.applicant')),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
    ]
