# Generated by Django 3.2.15 on 2022-09-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='approved_date',
            field=models.DateTimeField(db_column='fecha_aprovacion', null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='cancelation_date',
            field=models.DateTimeField(db_column='fecha_cancelacion', null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='completed_date',
            field=models.DateTimeField(db_column='fecha_completado', null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='denied_date',
            field=models.DateTimeField(db_column='fecha_rechazo', null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_solicitud'),
        ),
    ]
