# Generated by Django 4.0.6 on 2022-07-25 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loanrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='amount_approved',
            field=models.DecimalField(db_column='monto_aprovado', decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='applicant',
            field=models.OneToOneField(db_column='solicitante_id', on_delete=django.db.models.deletion.CASCADE, related_name='loan_request', to='loanrequest.applicant'),
        ),
    ]
