# Generated by Django 3.2.15 on 2022-08-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(db_column='numero', max_length=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='celphone',
            field=models.CharField(db_column='celular', max_length=12),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='tel',
            field=models.CharField(db_column='telefono', max_length=12),
        ),
        migrations.AlterField(
            model_name='employmentdata',
            name='building',
            field=models.CharField(db_column='edificio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employmentdata',
            name='number',
            field=models.CharField(db_column='numero', max_length=10),
        ),
        migrations.AlterField(
            model_name='employmentdata',
            name='tel',
            field=models.CharField(db_column='telefono', max_length=12),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='referer',
            field=models.CharField(max_length=260, null=True),
        ),
    ]
