# Generated by Django 3.2.15 on 2022-09-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanrequest', '0002_auto_20220913_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='referer',
            field=models.CharField(db_column='remitente', max_length=260, null=True),
        ),
    ]
