# Generated by Django 3.2.15 on 2022-08-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanrequest', '0002_auto_20220812_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='date',
            field=models.DateField(auto_now_add=True, db_column='fecha_solicitud'),
        ),
    ]
