# Generated by Django 4.0.6 on 2022-07-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanrequest', '0002_alter_loanrequest_amount_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='facebook',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='instagram',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(db_column='nacionalidad', default='Republica Dominicana', max_length=60),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='twitter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employmentdata',
            name='tel_ext',
            field=models.CharField(db_column='extension_tel', max_length=4, null=True),
        ),
    ]
