# Generated by Django 3.2.15 on 2022-08-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanrequest', '0003_alter_loanrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('VALIDANDO', 'validando'), ('COMPLETADO', 'completado'), ('RECHAZADO', 'rechazado'), ('CANCELADO', 'cancelado'), ('APROBADO', 'aprobado')], db_column='estatus_solicitud', default='VALIDANDO', max_length=10),
        ),
    ]
