# Generated by Django 3.2.15 on 2022-08-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanrequest', '0004_alter_loanrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentdata',
            name='other_income',
            field=models.DecimalField(db_column='otros_ingresos', decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='canceled_motive',
            field=models.CharField(db_column='motivo_cancelacion', max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='denied_motive',
            field=models.CharField(db_column='motivo_rechazo', max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='notes',
            field=models.CharField(db_column='notas_generales', max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_type',
            field=models.CharField(choices=[('B', 'comercial'), ('V', 'vehiculos'), ('P', 'personal'), ('H', 'vivienda')], db_column='tipo_prestamo', default='P', max_length=2),
        ),
    ]
