# Generated by Django 3.2.15 on 2022-08-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanrequest', '0005_auto_20220818_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='date',
            new_name='request_date',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='approved_date',
            field=models.DateField(db_column='fecha_aprovacion', null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='cancelation_date',
            field=models.DateField(db_column='fecha_cancelacion', null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='denied_date',
            field=models.DateField(db_column='fecha_rechazo', null=True),
        ),
    ]
