# Generated by Django 3.2.15 on 2022-08-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanrequest', '0006_auto_20220820_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='completed_date',
            field=models.DateField(db_column='fecha_completado', null=True),
        ),
    ]
