# Generated by Django 3.2.15 on 2022-08-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanrequest', '0007_loanrequest_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='tel',
            field=models.CharField(db_column='telefono', max_length=12, null=True),
        ),
    ]
